import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export const metadata = {
  title: "Terms of Service — Kiyo",
  description: "Terms governing your use of the Kiyo AI shopping assistant and Kapruka order services.",
};

const LAST_UPDATED = "1 June 2025";

export default function TermsPage() {
  return (
    <div className="flex h-full w-full justify-center overflow-y-auto">
    <div className="mx-auto w-full max-w-2xl px-4 py-8 animate-fade-up">

      <Link
        href="/"
        className="mb-8 inline-flex items-center gap-2 text-[13px] transition-colors"
        style={{ color: "var(--ink-3)" }}
      >
        <ArrowLeft className="h-3.5 w-3.5" />
        Back to <span className="font-kiyo">KI<span className="gradient-text">YO</span></span>
      </Link>

      <div className="mb-10">
        <p className="text-[12px] font-bold tracking-widest uppercase mb-3" style={{ color: "var(--purple-light)" }}>
          Legal
        </p>
        <h1 className="text-[32px] font-bold leading-tight text-foreground mb-3">
          Terms of Service
        </h1>
        <p className="text-[13px]" style={{ color: "var(--ink-3)" }}>
          Last updated: {LAST_UPDATED}
        </p>
      </div>

      <div className="flex flex-col gap-8 text-[14px] leading-relaxed" style={{ color: "var(--ink-2)" }}>

        <Section title="1. Acceptance">
          <p>
            By accessing or using <span className="font-kiyo">KI<span className="gradient-text">YO</span></span> (the &ldquo;Service&rdquo;), you agree to be bound by these Terms of
            Service. If you do not agree, do not use the Service. The Service is operated by
            Kapruka Holdings (Pvt) Ltd (&ldquo;Kapruka&rdquo;, &ldquo;we&rdquo;, &ldquo;our&rdquo;), incorporated in Sri Lanka.
          </p>
        </Section>

        <Section title="2. Description of Service">
          <p>
            <span className="font-kiyo">KI<span className="gradient-text">YO</span></span> is an AI-powered shopping assistant that enables users to discover products
            available on Kapruka.com and place orders through natural-language conversation.
            <span className="font-kiyo">KI<span className="gradient-text">YO</span></span> is an interface layer; all orders, payments, and deliveries are fulfilled by
            Kapruka under Kapruka&apos;s own terms and conditions.
          </p>
        </Section>

        <Section title="3. Eligibility">
          <ul className="flex flex-col gap-2 list-none">
            <Li>You must be at least 18 years old to place an order through <span className="font-kiyo">KI<span className="gradient-text">YO</span></span>.</Li>
            <Li>You must provide accurate delivery and contact information when requested.</Li>
            <Li>You are responsible for any orders placed from your device or session.</Li>
          </ul>
        </Section>

        <Section title="4. Orders and Payments">
          <ul className="flex flex-col gap-2 list-none">
            <Li>All prices are displayed in Sri Lankan Rupees (LKR) and are inclusive of applicable taxes unless stated otherwise.</Li>
            <Li>Placing an order through <span className="font-kiyo">KI<span className="gradient-text">YO</span></span> constitutes an offer to purchase; the contract is formed upon Kapruka&apos;s order confirmation.</Li>
            <Li>Payment is processed via Kapruka&apos;s secure checkout. <span className="font-kiyo">KI<span className="gradient-text">YO</span></span> does not handle or store card details.</Li>
            <Li>Payment links generated by <span className="font-kiyo">KI<span className="gradient-text">YO</span></span> expire after 60 minutes. Expired links cannot be reactivated; a new order must be placed.</Li>
            <Li>Kapruka reserves the right to cancel an order if a product becomes unavailable after the order is placed, in which case a full refund will be issued.</Li>
          </ul>
        </Section>

        <Section title="5. Delivery">
          <ul className="flex flex-col gap-2 list-none">
            <Li>Delivery availability, timelines, and charges are determined by Kapruka and may vary by product and location.</Li>
            <Li>Estimated delivery windows shown by <span className="font-kiyo">KI<span className="gradient-text">YO</span></span> are indicative. Kapruka is not liable for delays caused by circumstances beyond its reasonable control.</Li>
            <Li>Delivery to remote areas may not always be available. <span className="font-kiyo">KI<span className="gradient-text">YO</span></span> will notify you if your specified location cannot be served.</Li>
          </ul>
        </Section>

        <Section title="6. Returns and Refunds">
          <p>
            Returns and refunds are governed by{" "}
            <a
              href="https://www.kapruka.com/policies/returns"
              target="_blank"
              rel="noopener noreferrer"
              className="underline underline-offset-2 transition-colors hover:text-foreground"
              style={{ color: "var(--purple-light)" }}
            >
              Kapruka's Return Policy
            </a>
            . Perishable items (cakes, flowers, food) are generally non-returnable once delivered.
            For quality issues, contact Kapruka support within 24 hours of delivery with photographic
            evidence.
          </p>
        </Section>

        <Section title="7. AI-Generated Content">
          <p>
            <span className="font-kiyo">KI<span className="gradient-text">YO</span></span> uses a large language model (such as Anthropic Claude, OpenAI GPT, or Google Gemini, depending on configuration) to generate responses. While we strive for accuracy:
          </p>
          <ul className="flex flex-col gap-2 list-none mt-2">
            <Li>AI responses may occasionally contain errors, inaccuracies, or outdated information.</Li>
            <Li>Product descriptions and availability shown by <span className="font-kiyo">KI<span className="gradient-text">YO</span></span> are sourced from Kapruka&apos;s live catalogue and are generally accurate, but the Kapruka product page is the authoritative source.</Li>
            <Li><span className="font-kiyo">KI<span className="gradient-text">YO</span></span>&apos;s responses do not constitute professional advice of any kind.</Li>
          </ul>
        </Section>

        <Section title="8. Acceptable Use">
          <p>You agree not to:</p>
          <ul className="flex flex-col gap-2 list-none mt-2">
            <Li>Use <span className="font-kiyo">KI<span className="gradient-text">YO</span></span> for any unlawful purpose or in violation of Sri Lankan law.</Li>
            <Li>Attempt to manipulate, jailbreak, or extract unintended behaviour from the AI.</Li>
            <Li>Place fraudulent orders or provide false information.</Li>
            <Li>Use automated tools, bots, or scrapers to access the Service without written permission.</Li>
            <Li>Interfere with or disrupt the Service's infrastructure or security mechanisms.</Li>
          </ul>
          <p className="mt-3">
            Violations may result in suspension of access and legal action where applicable.
          </p>
        </Section>

        <Section title="9. Intellectual Property">
          <p>
            All content, branding, and software comprising <span className="font-kiyo">KI<span className="gradient-text">YO</span></span> are owned by Kapruka Holdings
            (Pvt) Ltd or its licensors. You may not reproduce, distribute, or create derivative
            works without express written consent. Conversation logs you generate remain your
            data, subject to the permissions described in our Privacy Policy.
          </p>
        </Section>

        <Section title="10. Fair Use">
          <p>
            <span className="font-kiyo">KI<span className="gradient-text">YO</span></span> is provided for personal shopping use. To keep the Service available and
            responsive for everyone, we may apply reasonable technical safeguards — such as
            request throttling — against usage patterns that look automated, abusive, or
            disruptive to the Service's infrastructure. Continued misuse may result in
            suspension of access.
          </p>
        </Section>

        <Section title="11. Disclaimer of Warranties">
          <p>
            The Service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of any kind,
            express or implied. Kapruka does not warrant that the Service will be uninterrupted,
            error-free, or that AI-generated responses will always be accurate or complete.
          </p>
        </Section>

        <Section title="12. Limitation of Liability">
          <p>
            To the maximum extent permitted by Sri Lankan law, Kapruka's total liability for
            any claim arising from use of <span className="font-kiyo">KI<span className="gradient-text">YO</span></span> is limited to the value of the order in dispute.
            Kapruka is not liable for indirect, incidental, or consequential damages.
          </p>
        </Section>

        <Section title="13. Governing Law">
          <p>
            These Terms are governed by the laws of the Democratic Socialist Republic of Sri Lanka.
            Disputes shall be subject to the exclusive jurisdiction of the courts of Colombo,
            Sri Lanka.
          </p>
        </Section>

        <Section title="14. Changes to Terms">
          <p>
            We may revise these Terms at any time. Continued use of <span className="font-kiyo">KI<span className="gradient-text">YO</span></span> after changes are posted
            constitutes acceptance of the updated Terms. Material changes will be reflected in
            the &ldquo;Last updated&rdquo; date above.
          </p>
        </Section>

        <Section title="15. Contact">
          <p>
            For legal enquiries, contact Kapruka Holdings (Pvt) Ltd:<br />
            <a
              href="mailto:colombo.office@kapruka.com"
              className="underline underline-offset-2 transition-colors hover:text-foreground"
              style={{ color: "var(--purple-light)" }}
            >
              colombo.office@kapruka.com
            </a>
            <br />
            147 Old Kottawa Road, Nugegoda 10250, Sri Lanka
          </p>
        </Section>

      </div>
    </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div
      className="rounded-2xl border p-5"
      style={{ background: "var(--surface)", borderColor: "var(--border)" }}
    >
      <p className="text-[15px] font-semibold text-foreground mb-3">{title}</p>
      {children}
    </div>
  );
}

function Li({ children }: { children: React.ReactNode }) {
  return (
    <li className="flex gap-2">
      <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full" style={{ background: "var(--purple-light)" }} />
      <span>{children}</span>
    </li>
  );
}
